//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vodi_Pro.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vodi_Pro.Properties.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   KAYDET benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0038 {
            get {
                return ResourceManager.GetString("S0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DÜZENLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0070 {
            get {
                return ResourceManager.GetString("S0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teslim Edildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0112 {
            get {
                return ResourceManager.GetString("S0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ücret Alındı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0116 {
            get {
                return ResourceManager.GetString("S0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0185 {
            get {
                return ResourceManager.GetString("S0185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MÜŞTERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0186 {
            get {
                return ResourceManager.GetString("S0186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NUMARA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0187 {
            get {
                return ResourceManager.GetString("S0187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MARKA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0188 {
            get {
                return ResourceManager.GetString("S0188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MODEL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0189 {
            get {
                return ResourceManager.GetString("S0189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARIZA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0190 {
            get {
                return ResourceManager.GetString("S0190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AÇIKLAMA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0191 {
            get {
                return ResourceManager.GetString("S0191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TESLİM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0192 {
            get {
                return ResourceManager.GetString("S0192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KAYIT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0193 {
            get {
                return ResourceManager.GetString("S0193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ALARM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0194 {
            get {
                return ResourceManager.GetString("S0194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teslim Edilmedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0202 {
            get {
                return ResourceManager.GetString("S0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ücret Alınmadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0203 {
            get {
                return ResourceManager.GetString("S0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HATA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0205 {
            get {
                return ResourceManager.GetString("S0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dolu satırlardan birini seçiniz!!! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0206 {
            get {
                return ResourceManager.GetString("S0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İnternet bağlnatısı hatası. Bağlantınız yok! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0207 {
            get {
                return ResourceManager.GetString("S0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UYARI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0208 {
            get {
                return ResourceManager.GetString("S0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silmek İstediğinizden Emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0209 {
            get {
                return ResourceManager.GetString("S0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen Bir Müşteri Seçiniz!!! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0210 {
            get {
                return ResourceManager.GetString("S0210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birden Fazla Müşteri Aynı Anda Görüntülenemez!!! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0211 {
            get {
                return ResourceManager.GetString("S0211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IMEI No 15 haneli olmalıdır!!! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0212 {
            get {
                return ResourceManager.GetString("S0212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verileri Excel&apos;e Aktarmak istediğinize Emin Misiniz ? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0213 {
            get {
                return ResourceManager.GetString("S0213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeniden Başlatılması Gerekiyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0214 {
            get {
                return ResourceManager.GetString("S0214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Gönderme İşlemi Başarılı... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0215 {
            get {
                return ResourceManager.GetString("S0215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İŞLEM YENİLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0217 {
            get {
                return ResourceManager.GetString("S0217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Geçmiş Zamana Ayarlanamaz!!! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0218 {
            get {
                return ResourceManager.GetString("S0218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesaj Gönderimi başarısız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0219 {
            get {
                return ResourceManager.GetString("S0219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlemizin Sırasında Bilinmeyen Bir Hata İle Karşılaşıldı. Bilgilerinizi Kontrol Ederek Tekrar deneyiniz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0220 {
            get {
                return ResourceManager.GetString("S0220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BİLGİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0221 {
            get {
                return ResourceManager.GetString("S0221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen VeriTabanının Yedekleneceği Dosya Yolunu Giriniz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0222 {
            get {
                return ResourceManager.GetString("S0222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen Bir Mail Adresi Giriniz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0223 {
            get {
                return ResourceManager.GetString("S0223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Yedeklenmesi Başarılı Bir şekilde Gerçekleşti... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0224 {
            get {
                return ResourceManager.GetString("S0224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Yedek VeriTabanı Dosyasıdır... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0225 {
            get {
                return ResourceManager.GetString("S0225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Müşteri Sayısı :  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0226 {
            get {
                return ResourceManager.GetString("S0226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cihazı Teslim Edilmeyen Müşteri Sayısı :  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0227 {
            get {
                return ResourceManager.GetString("S0227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı zaten kullanılmaktadır... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0228 {
            get {
                return ResourceManager.GetString("S0228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Listesi Müşteri Sayısı :  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0229 {
            get {
                return ResourceManager.GetString("S0229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Adresi veya Şifre Girilmemiş!!! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0230 {
            get {
                return ResourceManager.GetString("S0230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demo Süreniz Dolmuştur!!! Lütfen Ürün Anahtarı Giriniz! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0231 {
            get {
                return ResourceManager.GetString("S0231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şuanda Demo Sürümü Kullanmaktasınız. Kalan Kullanma Hakkınız :  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0232 {
            get {
                return ResourceManager.GetString("S0232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Bilgileri Girilmeden Kayıt Yapılamaz!!! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string S0233 {
            get {
                return ResourceManager.GetString("S0233", resourceCulture);
            }
        }
    }
}
